ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_markw/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
